### ISSUE TITLE
v 3.4.0 has no SSE bins

### ISSUE THREAD

**Issue by oeai** [VASTDynamics/Vaporizer2#47]
not sure if there are x32 and x64 or x64 only, but for 3.3.0 there was that _SSE vst3 and execs are working for my old CPU, it's not now.
i think you got wrong code for compile.bat because you need to pass both flags and join the compiler string for two cases, but you got just "else if" and you need maybe the switch case construction  command_compiler_string +=
also for Inno setup you can create registry strings to get the previous installed location also for waves/presets and maybe some setup.xml strings to leave it for MIDI-CC strings only.
not sure what was changed on last version. as for installer had some freezes when extracting some files, maybe because it misses them or can't overwrite something.
maybe i would change the way of downloading everything for downloading bins only, if users already has those waves/presets/etc maybe to a model of downloading within GUI or installer, maybe it just hanged while it was extracting some heavy files. you will be able to sell some preset banks after that - just for dev support.

**Comment by VASTDynamics** [comment]
Hi there, 
in 3.4.0 the filenames were changed (they were not standard and created problems in CMake). But the installer has two options that create what was there before: 
1) SSE2 versions .... this will install the SSE2 version instead of the AVX version. You should use this in case your system is too old.
2) Install old plugin names .... this will use the old _64.* and ._64_SSE names in case you still want to have them.
See here:
![image](https://github.com/VASTDynamics/Vaporizer2/assets/35850267/b74b76e8-92d9-4b9c-8a96-40b1b58f9692)

I never had the case that the insatller hangs. But there is a copy step at the very end (copying wavetables and samples) that can cause trouble when you are not administrator or have special folder access rights (e.g. no acces to your user-documents folder).

**Comment by oeai** [comment]
i did this few times and redownloaded .zip, but there's no any _sse file , like it was for 3.3.0, not for vst3,2 and in the install folder too
![vapr2](https://github.com/VASTDynamics/Vaporizer2/assets/2557665/c70e7fc2-6c51-4ada-99c5-61839885a78c)
![2023-12-06_02-31-04](https://github.com/VASTDynamics/Vaporizer2/assets/2557665/535dc140-8244-403b-821f-f2717bafe93b)
and also it was unable to overwrite files previously installed by installer.

**Comment by VASTDynamics** [comment]
Please check the pre-release - it should fix it:
[https://github.com/VASTDynamics/Vaporiz ... ag/v.3.4.1](https://github.com/VASTDynamics/Vaporizer2/releases/tag/v.3.4.1)
Or direct download for Windows (I am building macOS later): [https://github.com/VASTDynamics/Vaporiz ... _3.4.1.zip](https://github.com/VASTDynamics/Vaporizer2/releases/download/v.3.4.1/Vaporizer2_installer_win_3.4.1.zip)

**Comment by oeai** [comment]
yes. thank you. it is installing now and there are those SSE exe and vsts, but it's not working.
i mean in the same time v3.3.0  - works from any place.
it says something about iCreateComponent for vst. 
for this CPU reason and sonar can't find it (can't invoke prob)
maybe it's about some new JUCE features as they've come to 7.0.9 from 7.0.7
not sure

**Comment by VASTDynamics** [comment]
Hello, I did some research and it turns out that this is related to the breaking VST3 structure change from files to folder bundles. There were other complaints about this. It seems that several hosts have problems with the optional moduleinfo.json file. I have created an installer that removes those. Could you uninstall / delete old .vst3s and try this pre-release?
https://github.com/VASTDynamics/Vaporizer2/releases/download/v.3.4.1/Vaporizer2_installer_win_3.4.2.zip
Thank you.
