### ISSUE TITLE
CPU spikes due to Auto Save in Bitwig

### ISSUE THREAD

**Issue by VASTDynamics** [VASTDynamics/Vaporizer2#59]
CPU spikes due to Auto Save in Bitwig

**Comment by xard-dev** [comment]
I can reproduce this issue in Linux and Ardour 8.1 and Ardour 8.2.

I had to disable auto saving due to heavy CPU usage when having 16 instances of Vaporizer2 on the same project: the project file size grows to around 36 MiB but every time the project is saved the DSP usage jumps up to 100% for couple of seconds stopping all audio.

**Comment by VASTDynamics** [comment]
Yes, I could reproduce it. See the spike below that happnes exactly every 60 seconds:
![image](https://github.com/VASTDynamics/Vaporizer2/assets/35850267/0cea7378-db48-42f0-a976-e4951dc786bd)

Bitwig seems to call getStateInformation() every other minute.
![image](https://github.com/VASTDynamics/Vaporizer2/assets/35850267/2490c850-dd97-467a-9ccb-009c4da111fb)

**Comment by VASTDynamics** [comment]
This is fixed here:
https://github.com/VASTDynamics/Vaporizer2/commit/1610748ee31f699356404c2f3e1ea3061727860a
